config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  #devise_for :users 

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :venues do
    resources :deals
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/deal.rb
class Deal < ApplicationRecord

  belongs_to :venue
  has_and_belongs_to_many :days


  def print_days
    days = ''
    self.days.each do |day|
      days += day.name + ' '
    end

    days
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_for_permissions

  def index
    @venue = Venue.find(params[:venue_id])
    @deals = @venue.deals.all
  end 

  # GET /venues/1
  # GET /venues/1.json
  def show
    @venue = Venue.find(params[:venue_id])
    @deal = @venue.deals.find(params[:id])
  end

  def new
    @venue = Venue.find(params[:venue_id])
    @deal = @venue.deals.new
  end
  
  def edit
    @venue = Venue.find(params[:venue_id])
    @deal = @venue.deals.find(params[:id])
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.find(params[:venue_id])
    @deal = @venue.deals.new(deal_params)
    @deal.start_time = @deal.start_time.in_time_zone('EST')
    @deal.start_time -= @deal.start_time.utc_offset

    respond_to do |format|
      if @deal.save
        format.html { redirect_to venue_deal_path(@venue, @deal), notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    @venue = Venue.find(params[:venue_id])
    @deal = @venue.deals.find(params[:id])
    @deal.update(deal_params)
    @deal.start_time = @deal.start_time.in_time_zone('EST')
    @deal.start_time -= @deal.start_time.utc_offset
    
    respond_to do |format|
      if @deal.save
        format.html { redirect_to venue_deal_path(@venue, @deal), notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue = Venue.find(params[:venue_id])
    @deal = @venue.deals.find(params[:id])
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to venue_deals_path(@venue.id), notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def deal_params
    params.require(:deal).permit(:title, :description, :expiration, :start_time, :hours_active, { day_ids:[] })
  end

  def check_for_permissions
    if ( current_user.role == 'admin' && current_user.approved? )

    else
      redirect_to root_path
    end
  end

end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<%= form_for [venue, deal] do |f| %>
  <% if deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :expiration %>
    <%= f.date_field :expiration %>
  </div>

  <div class="field">
      <% for day in Day.all %>
          <div>
              <%= check_box_tag "deal[day_ids][]", day.id, deal.days.include?(day) %>
              <%= day.name %>
          </div>
      <% end %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.time_field :start_time %>
  </div>

  <div class="field">
    <%= f.label :hours_active %>
    <%= f.text_field :hours_active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1><%= @venue.name %> - <%= @deal.title %> - Editing Deal</h1>

<%= render 'form', venue: @venue, deal: @deal %>

<%= link_to 'Show', venue_deal_path(@venue, @deal) %> |
<%= link_to 'Back', venue_deals_path(@venue) %>

app/views/deals/index.html.erb
<h1><%= @venue.name %> - Deals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Expiration</th>
      <th>Days</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @venue.deals.each do |deal| %>
      <tr>
        <td><%= deal.title %></td>
        <td><%= deal.description %></td>
        <td><%= deal.expiration.strftime("%m/%d/%Y") %></td>
        <td><%= deal.print_days %></td>
        <td><%= deal.start_time.in_time_zone("EST").strftime("%I:%M %p") %></td>
        <td><%= ( deal.start_time.in_time_zone("EST") + ( deal.hours_active*60*60 ) ).strftime("%I:%M %p") %></td>
        <td><%= link_to 'Show', venue_deal_path(@venue, deal) %></td>
        <td><%= link_to 'Edit', edit_venue_deal_path(@venue, deal) %></td>
        <td><%= link_to 'Destroy', venue_deal_path(@venue, deal), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deal', new_venue_deal_path(@venue.id) %> |
<%= link_to 'Back', venues_path %>

app/views/deals/new.html.erb
<h1><%= @venue.name %> - Create New Deal</h1>

<%= render 'form', venue: @venue, deal: @deal %>

<%= link_to 'Back', venue_deals_path(@venue) %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @venue.name %> - Deal</h1>

<p>
  <strong>Title:</strong>
  <%= @deal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deal.description %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @deal.expiration.strftime("%m/%d/%Y") %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @deal.print_days %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @deal.start_time.in_time_zone("EST").strftime("%I:%M %p") %>
</p>

<p>
  <strong>End Time:</strong>
  <%= ( @deal.start_time.in_time_zone("EST") + ( @deal.hours_active*60*60 ) ).strftime("%I:%M %p") %>
</p>

<%= link_to 'Edit', edit_venue_deal_path(@venue, @deal) %> |
<%= link_to 'Back', venue_deals_path(@venue) %>